package Model.simulation.model;

public enum EventType {
    B1_PASSENGER_ARRIVAL,B2_PASSENGER_ARRIVAL,
    B3_TICKET_CHECK_FINISH,B4_TICKET_CHECK_FINISH,
    B5_TRAIN1_DEPARTURE, B6_TRAIN2_DEPARTURE, B7_TRAIN3_DEPARTURE,
    B8_TRAIN1_ARRIVAL, B9_TRAIN2_ARRIVAL, B10_TRAIN3_ARRIVAL,
}
